@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Sep 30 10:39:48 -0500 2020
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim DataMem_tb_behav -key {Behavioral:sim_1:Functional:DataMem_tb} -tclbatch DataMem_tb.tcl -view C:/Users/19136/Documents/dev/eecs-645/hw5/HW05_MIPS_MEM_Kline/DataMem/simulation_sources/DataMem_wave.wcfg -log simulate.log"
call xsim  DataMem_tb_behav -key {Behavioral:sim_1:Functional:DataMem_tb} -tclbatch DataMem_tb.tcl -view C:/Users/19136/Documents/dev/eecs-645/hw5/HW05_MIPS_MEM_Kline/DataMem/simulation_sources/DataMem_wave.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
