webtalk_init -webtalk_dir C:/Users/e190a104/Desktop/HW04_MIPS_RegFile_Solution/vivado_project/vivado_project.sim/sim_1/behav/xsim/xsim.dir/regfile_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Sep 17 12:07:39 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "177979535_1777511266_210706886_766" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ae6e3937-9bda-4f02-81fd-96d37b4d92ac" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a4fa08d098654964b85632d4baeeb640" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "7" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) E-2124 CPU @ 3.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3312 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "300 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "11264_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2692573520 -regid "177979535_1777511266_210706886_766" -xml C:/Users/e190a104/Desktop/HW04_MIPS_RegFile_Solution/vivado_project/vivado_project.sim/sim_1/behav/xsim/xsim.dir/regfile_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/e190a104/Desktop/HW04_MIPS_RegFile_Solution/vivado_project/vivado_project.sim/sim_1/behav/xsim/xsim.dir/regfile_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/e190a104/Desktop/HW04_MIPS_RegFile_Solution/vivado_project/vivado_project.sim/sim_1/behav/xsim/xsim.dir/regfile_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
