@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Sep 09 07:16:53 -0500 2020
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim mod_m_up_dn_count_tb_behav -key {Behavioral:sim_1:Functional:mod_m_up_dn_count_tb} -tclbatch mod_m_up_dn_count_tb.tcl -view C:/Users/19136/Documents/dev/eecs-645/hw2/HW02_Type_Mismatch_Kline/mod_m_up_dn_count/simulation_sources/mod_m_up_dn_count_wave.wcfg -log simulate.log"
call xsim  mod_m_up_dn_count_tb_behav -key {Behavioral:sim_1:Functional:mod_m_up_dn_count_tb} -tclbatch mod_m_up_dn_count_tb.tcl -view C:/Users/19136/Documents/dev/eecs-645/hw2/HW02_Type_Mismatch_Kline/mod_m_up_dn_count/simulation_sources/mod_m_up_dn_count_wave.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
