webtalk_init -webtalk_dir C:/Users/19136/Documents/dev/eecs-645/hw1/HW01_VSim_Tutorial_Kline/mod_m_up_dn_count/hw1_mod_m_up_dn_count/hw1_mod_m_up_dn_count.sim/sim_1/behav/xsim/xsim.dir/mod_m_up_dn_count_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Sep  2 17:20:27 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "95d7058d-bea3-4e65-b718-1f0abe7fe0d2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "1702ea8a0b67437b9cf2061df1ac2252" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6500_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3258601172 -regid "" -xml C:/Users/19136/Documents/dev/eecs-645/hw1/HW01_VSim_Tutorial_Kline/mod_m_up_dn_count/hw1_mod_m_up_dn_count/hw1_mod_m_up_dn_count.sim/sim_1/behav/xsim/xsim.dir/mod_m_up_dn_count_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/19136/Documents/dev/eecs-645/hw1/HW01_VSim_Tutorial_Kline/mod_m_up_dn_count/hw1_mod_m_up_dn_count/hw1_mod_m_up_dn_count.sim/sim_1/behav/xsim/xsim.dir/mod_m_up_dn_count_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/19136/Documents/dev/eecs-645/hw1/HW01_VSim_Tutorial_Kline/mod_m_up_dn_count/hw1_mod_m_up_dn_count/hw1_mod_m_up_dn_count.sim/sim_1/behav/xsim/xsim.dir/mod_m_up_dn_count_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
